name: atomic
on:
  push:
    branches: main
    paths: docs/epub/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configuring user/email for (local) git commits
        run: |
          git config --global user.name "${USER_NAME}"
          git config --global user.email "${USER_NAME}@users.noreply.github.com"
        env:
          USER_NAME: ${{github.actor}}
      - name: Checking out
        uses: actions/checkout@v2
      - name: Regenerating the epub file from the contents of the docs/epub directory
        run: zip docs/ebook.epub docs/epub/*
      - name: Commiting and pushing docs/epub directory contents
        run: |
          git add docs/ebook.epub
          git commit -m "Derived from an update on the directory docs/epub"
          git push
