name: Build and (if configured) publish
on:
  push:
    branches: main
    paths: editable/excerpt.html
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Java code used by this build
        run: wget --no-verbose https://ebookipedia.github.io/java/build.jar
      - name: Checking out the files in this repository
        uses: actions/checkout@v1
      - name: Configuring user/email to be used for git commits
        run: |
          git config --global user.name "${USER_NAME}"
          git config --global user.email "${USER_NAME}@users.noreply.github.com"
        env:
          USER_NAME: ${{github.actor}}
      - name: Building (publishable) docs/excerpt.html from editable/excerpt.html and detecting the mirrored article
        run: |
          export GITHUB_OAUTH=${{secrets.GITHUB_TOKEN}}
          java -cp build.jar updated.Excerpt
          git add docs/excerpt.html
          git commit -m "(automated) adapt edited excerpt.html to be published"
          git push
      - name: Generating the epub of the mirrored article (using mediawiki2latex) if it was not generated yet
          if [ ! -f docs/article.epub2 ]; then
            sudo apt-get install mediawiki2latex
            mediawiki2latex --epub --url="$(<.java-generated/mirrored-article)" --output="docs/article.epub2"
            git add docs/source.epub
            git commit -m "(automated) epub generated by mediawiki2latex"
            git push
          fi
