name: Build
on:
  push:
    branches: main
    paths: editable/excerpt.html
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the files in this repository
        uses: actions/checkout@v2
      - name: Downloading Java code used by this build
        run: wget --no-verbose https://ebookipedia.github.io/java/build.jar
      - name: Configuring user/email to be used for git commits
        run: |
          git config --global user.name "${USER_NAME}"
          git config --global user.email "${USER_NAME}@users.noreply.github.com"
        env:
          USER_NAME: ${{github.actor}}
      - name: Building docs/excerpt.html from editable/excerpt.html and detecting the mirrored article
        run: |
          export GITHUB_OAUTH=${{secrets.GITHUB_TOKEN}}
          java -cp build.jar updated.Excerpt $GITHUB_REPOSITORY
          git add docs/excerpt.html
          git commit -m "(automated) adapted from modified editable/excerpt.html"
      - name: Generating the epub2 version of the mirrored article (using mediawiki2latex) if not generated yet
        id: checking
        uses: andstor/file-existence-action@v1
        with:
          files: "*.epub"
      - if: steps.checking.outputs.files_exists == 'false'
        uses: ebookipedia/epub@main
        with:
          title: "x"
          url: "y"
      - name: Pushing changes
        run: git push
