name: epub
on:
  push:
    branches: main
    paths: docs/ebook.epub
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configuring user/email for (local) git commits
        run: |
          git config --global user.name "${USER_NAME}"
          git config --global user.email "${USER_NAME}@users.noreply.github.com"
        env:
          USER_NAME: ${{github.actor}}
      - name: Checking out
        uses: actions/checkout@v2
      - name: Generating (or removing) the docs/epub directory based on the contents of the epub file
        run: |
          if test -f docs/ebook.epub; then
            mkdir -p docs/epub
            unzip docs/ebook.epub -d docs/epub
          else
            rm -R docs/epub
          fi
      - name: Commiting and pushing docs/epub directory contents
        run: |
          git add docs/epub/*
          git commit -m "Derived from an update of the epub file"
          git push
