name: Process index.html content
on:
  push:
    branches: [ main ]
    paths:
      - src/excerpt.html
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - run: wget https://ebookipedia.github.io/java/build.jar
      - run: java -cp build.jar mirror.Wikipedia $GITHUB_REPOSITORY
      - run: | 
          if [ ! -f source.epub ]; then
            echo "writing source.epub"
            #sudo apt-get install mediawiki2latex
            #mediawiki2latex --epub -u ${{ env.url }}
            echo "Hello, World" > source.epub
          fi
