name: Process index.html content
on:
  push:
    branches: [ main ]
    paths:
      - index.html
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ebookipedia/setup-java@main
      - run: wget https://ebookipedia.github.io/wikipedia/build.jar
      - run: java -jar build.jar $GITHUB_REPOSITORY index
