name: Process index.html content
on:
  push:
    branches: [ main ]
    paths:
      - index.html
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'temerin'
          java-version: '8'
      - run: wget https://ebookipedia.github.io/java/build.jar
      - run: java -cp build.jar mirror.Wikipedia $GITHUB_REPOSITORY
