name: Build editable/summary.html
on:
  push:
    branches: main
    paths: editable/summary.html
jobs:
  initialize:
    name: Preparing the environment
    runs-on: ubuntu-latest
    steps:
      - name: Configuring user/email for (local) git commits
        run: |
          git config --global user.name "${USER_NAME}"
          git config --global user.email "${USER_NAME}@users.noreply.github.com"
        env:
          USER_NAME: ${{github.actor}}
      - name: Checking out
        uses: actions/checkout@v2
      - name: Downloading the needed Java code
        run: wget --no-verbose https://ebookipedia.github.io/java/build.jar
  html:
    name: Generating the (publishable) docs/summary.html from the contents of the (updated) editable/summary.html and storing the title and URL of the mirrored content
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - name: Running the Java code
        run: |
          export GITHUB_OAUTH=${{secrets.GITHUB_TOKEN}} # this system settting is not used yet
          java -cp build.jar updated.Summary $GITHUB_REPOSITORY # this parameter is not used yet
      - name: Saving the title and the URL of the mirrored document
        id: I
          echo ::set-output name=title::$(<.java-generated/title)
          echo ::set-output name=url::$(<.java-generated/url)
      - name: Commiting
        run: |
          git add docs/summary.html
          git commit -m "Derived from an update of editable/excerpt.html"
      - name: Checking if exists locally an ebook (epub) with the mirrored content
        id: II
        uses: andstor/file-existence-action@v1
        with:
          files: "docs/${{steps.I.outputs.title}}.epub"
  ebook:
    if: steps.II.outputs.files_exists == 'false'
    name: Generating the epub version of the mirrored article if not generated yet
    needs: [initialize, html]
    runs-on: ubuntu-latest
    steps:
      - name: Getting the epub file
        uses: ebookipedia/epub@main
        with:
          title: ${{steps.I.outputs.title}}
          url: ${{steps.I.outputs.url}}
      - name: Moving the downloaded epub to /docs and committing
        run: |
          mv "$EBOOK_TITLE" docs
          git add "docs/$EBOOK_TITLE"
          git commit -m "Derived from ${{steps.I.outputs.url}} (ebookinet/epub-press)"
        env:
          EBOOK_TITLE: "${{steps.I.outputs.title}}.epub"
  push:
    name: Push
    needs: [html, ebook]
    runs-on: ubuntu-latest
    steps:
      - name: Pushing
        run: git push
