name: Summary
on:
  push:
    branches: main
    paths: editable/summary.html
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configuring user/email for (local) git commits
        run: |
          git config --global user.name "${USER_NAME}"
          git config --global user.email "${USER_NAME}@users.noreply.github.com"
        env:
          USER_NAME: ${{github.actor}}
      - name: Checking out
        uses: actions/checkout@v2
      - name: Downloading the needed Java code
        run: wget --no-verbose https://ebookipedia.github.io/java/build.jar
      - name: Generating the docs/summary.html from editable/summary.html and storing title and URL of the mirrored content
        id: I
        run: |
          export GITHUB_OAUTH=${{secrets.GITHUB_TOKEN}} # this system settting is not used yet
          java -cp build.jar updated.Summary $GITHUB_REPOSITORY # this parameter is not used yet
          echo ::set-output name=title::$(<.java-generated/title)
          echo ::set-output name=url::$(<.java-generated/url)
      - name: Commiting docs/summary.html
        run: |
          git add docs/summary.html
          git commit -m "Derived from an update of editable/summary.html"
      - name: Checking for the existence of an epub file with the mirrored content
        id: II
        uses: andstor/file-existence-action@v1
        with:
          files: "docs/ebook.epub"
      - if: steps.II.outputs.files_exists == 'false'
        name: Getting the epub file
        uses: ebookipedia/epub@main
        with:
          title: ${{steps.I.outputs.title}}
          url: ${{steps.I.outputs.url}}
      - if: steps.II.outputs.files_exists == 'false'
        name: Moving the downloaded epub to /docs and committing it
        run: |
          mv "$EBOOK_TITLE" docs/ebook.epub
          git add "docs/ebook.epub"
          git commit -m "Derived from ${{steps.I.outputs.url}}"
        env:
          EBOOK_TITLE: "${{steps.I.outputs.title}}.epub"
      - name: Pushing the committed contents
        run: git push
